// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystemetAPI.Models;

namespace SystemetAPI.Migrations
{
    [DbContext(typeof(VRContext))]
    [Migration("20190404090823_Inital")]
    partial class Inital
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SystemetAPI.Models.SysSortTable", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Alkoholhalt");

                    b.Property<int?>("Argang");

                    b.Property<int>("ArtikelId");

                    b.Property<bool>("Ekolokisk");

                    b.Property<bool>("Etiskt");

                    b.Property<string>("Forpackning");

                    b.Property<string>("Forslutning");

                    b.Property<bool>("Koscher");

                    b.Property<string>("Land");

                    b.Property<string>("Leverantör");

                    b.Property<string>("Namn");

                    b.Property<string>("Namn2");

                    b.Property<int>("Nr");

                    b.Property<int>("Pant");

                    b.Property<decimal>("PrisInkMoms");

                    b.Property<decimal>("PrisPerLiter");

                    b.Property<string>("Producent");

                    b.Property<int?>("Provadarargang");

                    b.Property<string>("RavarorDesc");

                    b.Property<DateTime?>("Saljstart");

                    b.Property<string>("Sortiment");

                    b.Property<string>("SortimentText");

                    b.Property<string>("Stil");

                    b.Property<string>("Typ");

                    b.Property<string>("Ursprung");

                    b.Property<bool>("Utgatt");

                    b.Property<string>("Varugrupp");

                    b.Property<int>("Varunummer");

                    b.Property<decimal>("VolymIml");

                    b.HasKey("ID");

                    b.ToTable("SysSortTable");
                });
#pragma warning restore 612, 618
        }
    }
}
